apiVersion: v1
name: cronjob-multi
version: 1.0.4
description: The Universal Cronjob Multi Helm Chart, to spin up many similar cronjobs
keywords:
  - cronjob
  - cronjob-multi
  - helm
home: https://github.com/MefistoBaal/Universal-Helm-Charts
sources:
  - https://github.com/MefistoBaal/Universal-Helm-Charts/charts/deployment
  - https://helm.mefistobaal.tech
maintainers:
  - name: MefistoBaal
    email: shurtado@ddoscom.tech
