name: Deploy

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

  workflow_dispatch:
    
jobs:
  build:
    name: Install all stuff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Install Tools"
        run: |
          cd scripts
          chmod +x install_tools.sh
          ./install_tools.sh